### ISSUE TITLE
下载发生错误

### ISSUE THREAD

**Issue by BigfanofGreenDay** [kuainx/science-reading-download#3]
console给出的报错：
Mixed Content: The page at 'https://wkobwp.sciencereading.cn/asserts/5ad0090faf1f479bb852c7fb75b00418/image/3/100?accessToken=accessToken&formMode=true' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://wkobwp.sciencereading.cn/asserts/5ad0090faf1f479bb852c7fb75b00418/image/0/100?accessToken=accessToken&formMode=true'. This request has been blocked; the content must be served over HTTPS.
getPage @ VM48:74
onclick @ 100?accessToken=accessToken&formMode=true:1

**Comment by kuainx** [comment]
我访问该链接返回空白内容
如报该错误建议将浏览器地址栏改为https再执行脚本

**Comment by kuainx** [comment]
已修复

**Comment by YaoLiMuMu** [comment]
现在还能用吗? 下载下来的是原格式吗

**Comment by kuainx** [comment]
> 现在还能用吗? 下载下来的是原格式吗

可以，图片格式

**Comment by YaoLiMuMu** [comment]
> > 现在还能用吗? 下载下来的是原格式吗
> 
> 可以，图片格式

有没有什么方法汇成一册变为pdf?

**Comment by kuainx** [comment]
> > > 现在还能用吗? 下载下来的是原格式吗
> > 
> > 
> > 可以，图片格式
> 
> 有没有什么方法汇成一册变为pdf?

全部下载下来之后使用例如adobe acrobat等软件合并文件为pdf，pdf内每页均为图片，如有需要文字识别，可自行使用acrobat的ocr等功能

**Comment by YaoLiMuMu** [comment]
啊, 我是linux 系统, 高中后就没用过window和平台下的软件

**Comment by YaoLiMuMu** [comment]
目前遇到问题, 一直卡者不动, 点击下载按钮和获取原文也没有用
![image](https://github.com/ekuai-ebook-dl/science-reading-download/assets/32826811/8ed07d66-b5c7-453f-a751-f1e692d36931)

**Comment by YaoLiMuMu** [comment]
我开个新的issue, 上传个console的log文件, 请看看是什么问题

**Comment by kuainx** [comment]
> 目前遇到问题, 一直卡者不动, 点击下载按钮和获取原文也没有用 ![image](https://private-user-images.githubusercontent.com/32826811/312469338-8ed07d66-b5c7-453f-a751-f1e692d36931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzU4ODcsIm5iZiI6MTcxMDMzNTU4NywicGF0aCI6Ii8zMjgyNjgxMS8zMTI0NjkzMzgtOGVkMDdkNjYtYjVjNy00NTNmLWE3NTEtZjFlNjkyZDM2OTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEzMTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYmE5YzA0YjMwZDRlMGZiNjY4MzkyYzZjYTA0NGJjYzI0MzkyNDJiYzMxMThmOGI2ZDZlNzY0ODQwZWM5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v6t76ZR0CsK3o6jRnmwFzY5wKBlogdeuvL3vo5KsS-E)

不用，interval时间调长一点，这个是访问太快了，服务端限制了，等一会再下

**Comment by kuainx** [comment]
> 我开个新的issue, 上传个console的log文件, 请看看是什么问题

你开吧，我过两天有空优化一下
