### ISSUE TITLE
下载图片卡在其中一个页面, 中断了无法继续

### ISSUE THREAD

**Issue by YaoLiMuMu** [kuainx/science-reading-download#4]
下载图片卡在其中一个页面, 中断了无法继续
重复点击"获取页面"和"下载"按钮也无济于事.
console 的log文件如下, 可能吧
[wkobwp.sciencereading.cn-1710336379794.log](https://github.com/ekuai-ebook-dl/science-reading-download/files/14588321/wkobwp.sciencereading.cn-1710336379794.log)
其他信息请参考: https://github.com/ekuai-ebook-dl/science-reading-download/issues/3

**Comment by kuainx** [comment]
更新一下脚本，并重新阅读一下readme，进行一下尝试，欢迎反馈有无效果
3/13日更新并未修改下载原理

**Comment by YaoLiMuMu** [comment]
我尝试一下, 已经成功下载了一本书了, 对于没有权限的书籍或者在校外网的人来说不错的workaround.
-----
另外, 开发者大哥, 我这边有个相似的问题, 如果你感兴趣的话, 可以一起讨论或者指导下我
1, 我有的时候需要参考阅读一些中国国家标准, 但是现在好多网站都不支持标准预览与下载, 好不容易找到一个网站(https://www.bzsb.info/searchStandard.do), 这个网站支持在线预览pdf, 并且pdf是可以支持文字检索和复制的, 甚至支持Ctrl+p打印的扫描版的pdf, 但是无法导出原生pdf
2. 我自己在网站上查询了下, 现在的网上pdf都是基于pdf.js的, 这个模块是有下载原pdf的方法的, 比如原先的国家标准公开平台可以在console 窗口执行PDFViewerApplication.save()的实例方法进行下载pdf, 后面官网就关闭原生pdf预览窗口功能了, 导致这个方法失效了
3. 那么我就在想, 我现在发现这个网站是否也有相似的破解方法, 我尝试了PDFViewerApplication.save()是失效的, 开发者的界面的element的html文件中src中也没有获取目标pdf文件源, 后来从你这个science-read-download 的readme步骤中得来的灵感, 在开发者模式下查看Nework界面, 重新刷新界面检查从服务端获取的信息内容, 最后定位到都是
https://www.bzsb.info/searchStandard.do?action=getPdf这样的网址, 这个网站是个服务端文件目录, 根本没有目标pdf文件. 就此, 我感觉到黔驴技穷了.
![image](https://github.com/ekuai-ebook-dl/science-reading-download/assets/32826811/0790a027-cf67-4af7-afb3-bc1cb556a562)


你看看我哪些疏忽或可以其他尝试的地方吗? 原谅我不是js和web开发者, 对于好多网页知识都很陌生, , 如果你愿意探讨破解这个问题的话, [这个网站的登录账户和密码请参考这里](https://www.bzsb.info/public/articleHtml/179_15013_1_view.html)

最后, 为避免讨论影响这个仓库下面的issue事件的处理, 其他用户和贡献者, 你可以直接联系我的中文邮箱(wo347522772@hotmail.com)

**Comment by kuainx** [comment]
https://github.com/ekuai-ebook-dl/bzsb.info
